"""Tests for the main module helper functions."""


def test_format_pr_comment_structure():
    """
    Verifies the structure of format_pr_comment output.
    
    We test the formatting logic directly to avoid module import issues
    with the LLM initialization that happens at import time.
    """
    # Replicate the format_pr_comment logic for testing
    provider = "anthropic"
    model = "claude-sonnet-4-20250514"
    roadmap_content = "## Review Roadmap\n\nThis is the roadmap content."
    
    header = f"""🗺️ **Auto-Generated Review Roadmap**

> This roadmap was automatically generated by [review-roadmap](https://github.com/jwm4/review-roadmap).
> Model: `{provider}/{model}`

---

"""
    result = header + roadmap_content
    
    # Check header
    assert "🗺️ **Auto-Generated Review Roadmap**" in result
    
    # Check attribution link
    assert "https://github.com/jwm4/review-roadmap" in result
    
    # Check model info format (provider/model)
    assert f"{provider}/{model}" in result
    
    # Check roadmap content is included at the end
    assert roadmap_content in result
    assert result.endswith(roadmap_content)
    
    # Check separator is present between header and content
    assert "---" in result
    
    # Verify the structure: header should come before separator, separator before content
    header_pos = result.find("Auto-Generated Review Roadmap")
    separator_pos = result.find("---")
    content_pos = result.find(roadmap_content)
    
    assert header_pos < separator_pos < content_pos


def test_format_pr_comment_preserves_content():
    """Verifies that the roadmap content is preserved exactly."""
    provider = "openai"
    model = "gpt-4o"
    
    # Test with complex markdown content
    roadmap_content = """## Files to Review

### 1. Core Changes
- `src/main.py` - Entry point changes
- `src/utils.py` - Helper functions

### 2. Tests
```python
def test_example():
    assert True
```

**Note**: This includes code blocks and special characters: <>&"'
"""
    
    header = f"""🗺️ **Auto-Generated Review Roadmap**

> This roadmap was automatically generated by [review-roadmap](https://github.com/jwm4/review-roadmap).
> Model: `{provider}/{model}`

---

"""
    result = header + roadmap_content
    
    # Content should be preserved exactly
    assert result.endswith(roadmap_content)
    
    # Special characters should not be escaped
    assert "<>&\"'" in result
